### ISSUE TITLE
AntiVirus Alerts

### ISSUE THREAD

**Issue by biggusbeardus** [sander1095/DnDInitiativeTracker#26]
I've never reported anything on GitHub before, so forgive me if I am in poor form.

When installing 2.1.6.0 of the CombatTracker.application all Windows bell's and whistles went off telling me not to install it.

I'm running Windows 10 Home version 1803 OS build 17134.228.

AVG doesn't seem to find it threatening, so I'm good.

Just thought I'd share.

Haven't tried the app yet. Thanks for sharing.

Later,

  BB

**Comment by sander1095** [comment]
Hello!

Thank you for submitting this issue. 

You getting alerts is VERY odd. Nothing in this code should alert a PC of viruses; all the code is legit and uses libraries written by Microsoft themselves.

Can you give me screenshots/detailed error messages of the alert?

Thanks!

**Comment by biggusbeardus** [comment]
I think it might be security certificate related or whatever that would be
called. It acted as if the app wasn't from a "trusted" source.

No "virus" alerts popped up or anything that said "threatening" BUT at
least 3 on this system popped up. All Windows based. No third party.

I'm no programmer and the little I do mess with is more design related web
stuff.

I'm just tellin ya what I saw pa... ;)

**Comment by sander1095** [comment]
I believe that was Windows Smart Screen. Because I made this software myself and it isn't signed by a real certificate, Windows warns you because it can't guarantee that this software isn't automatically trusted by Windows. 


A certificate in this sense is a "thing" saying that this software is trusted. Software can obtain this certificate by buying it from a company that has the authority to (dis)trust certain software.

Because this software is free and I made it myself, I will not buy such a thing. 

I can 100% promise you this software is virus free :) I hope you can trust my words!

If you want more information, please say so. Otherwise, close this issue :)! 

If you do decide to use this program and you have some feedback, please create a new issue <3

PS: Just checked out your site (dmninja)! Great to see you being passionate about D&D!
